//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POOII_CL3_Rodríguez_León_Mitchell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public int ViajeId { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<int> VehiculoId { get; set; }
        public Nullable<int> ConductorId { get; set; }
        public Nullable<System.DateTime> FechaPartida { get; set; }
        public Nullable<System.DateTime> FechaLlegada { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
